language: java
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
before_install:
  # clone java-dirq repo
  - git clone --depth=100 --quiet --branch=master git://github.com/cern-mig/java-dirq.git java-dirq-git
  - cd java-dirq-git
  - mvn clean install
  - cd ../

