notifications:
  email:
    - mig-travis@cern.ch
language: java
jdk:
  - openjdk9
  - openjdk11
  - openjdk13
  - oraclejdk11
  - oraclejdk13
before_install:
  # clone java-dirq repo
  - git clone --depth=100 --quiet --branch=master git://github.com/cern-mig/java-dirq.git java-dirq-git
  - cd java-dirq-git
  - mvn -Dmaven.javadoc.skip=true clean install
  - cd ../
